# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Algorithmic Composition
author: Benedikt Zönnchen
email: benedikt.zoennchen@web.de
logo: figs/logo.png
copyright: '2022'
only_build_toc_files: true

execute:
  execute_notebooks: force
latex:
  latex_documents:
    targetname: book.tex
bibtex_bibfiles:
  - references.bib
sphinx:
  extra_extensions:
  - sphinx_exercise
  - sphinx_inline_tabs
  config:
    language: en
    nb_render_text_lexer: "none"
    pygments_style: "material"
    html_theme: "sphinx_book_theme"
    myst_enable_extensions: ["dollarmath", "amsmath", "colon_fence", "deflist"]
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

latex:
  latex_documents:
    targetname: book.tex